// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBhmgCsm-yCHjXiW-TE5wjty0sZWgT0As',
    appId: '1:387272003387:web:da41543452d69828b3b11e',
    messagingSenderId: '387272003387',
    projectId: 'clon-ubereat',
    authDomain: 'clon-ubereat.firebaseapp.com',
    storageBucket: 'clon-ubereat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tMPI0ou3stzRnNSKRi2p1JB4KZizRbM',
    appId: '1:387272003387:android:063e325bb4a2b1e7b3b11e',
    messagingSenderId: '387272003387',
    projectId: 'clon-ubereat',
    storageBucket: 'clon-ubereat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL4Fz2t2YsT778c1bt65U3NEKK0iju7JM',
    appId: '1:387272003387:ios:c312adf95591f44fb3b11e',
    messagingSenderId: '387272003387',
    projectId: 'clon-ubereat',
    storageBucket: 'clon-ubereat.firebasestorage.app',
    iosBundleId: 'com.example.clonubereat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL4Fz2t2YsT778c1bt65U3NEKK0iju7JM',
    appId: '1:387272003387:ios:c312adf95591f44fb3b11e',
    messagingSenderId: '387272003387',
    projectId: 'clon-ubereat',
    storageBucket: 'clon-ubereat.firebasestorage.app',
    iosBundleId: 'com.example.clonubereat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBhmgCsm-yCHjXiW-TE5wjty0sZWgT0As',
    appId: '1:387272003387:web:74c994c1d3a4b9eab3b11e',
    messagingSenderId: '387272003387',
    projectId: 'clon-ubereat',
    authDomain: 'clon-ubereat.firebaseapp.com',
    storageBucket: 'clon-ubereat.firebasestorage.app',
  );
}
